"""empty message

Revision ID: f473cf0f977e
Revises: 
Create Date: 2023-12-11 17:21:23.052140

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f473cf0f977e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('approval_requests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('requestedby', sa.String(), nullable=False),
    sa.Column('approvalstatus', sa.Integer(), nullable=True),
    sa.Column('filename', sa.String(), nullable=True),
    sa.Column('requestedon', sa.DateTime(), nullable=True),
    sa.Column('type', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('category',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=60), nullable=False),
    sa.Column('createdon', sa.DateTime(), nullable=True),
    sa.Column('approvalstatus', sa.Integer(), nullable=True),
    sa.Column('requestedby', sa.String(), nullable=True),
    sa.Column('createdby', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('isactive', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('product',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=60), nullable=True),
    sa.Column('createdon', sa.DateTime(), nullable=True),
    sa.Column('category', sa.Integer(), nullable=True),
    sa.Column('unit', sa.String(length=100), nullable=True),
    sa.Column('rate', sa.Integer(), nullable=True),
    sa.Column('qty', sa.Integer(), nullable=True),
    sa.Column('active', sa.Integer(), nullable=True),
    sa.Column('img', sa.String(), nullable=True),
    sa.Column('createdby', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('store',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('createdby', sa.String(), nullable=False),
    sa.Column('storename', sa.String(length=60), nullable=True),
    sa.Column('isactive', sa.Integer(), nullable=True),
    sa.Column('createdon', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('userid', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=True),
    sa.Column('email', sa.String(length=60), nullable=True),
    sa.Column('usertype', sa.Integer(), nullable=False),
    sa.Column('isactive', sa.Integer(), nullable=True),
    sa.Column('storeid', sa.Integer(), nullable=True),
    sa.Column('createdon', sa.DateTime(), nullable=True),
    sa.Column('password', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('userid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('store')
    op.drop_table('product')
    op.drop_table('category')
    op.drop_table('approval_requests')
    # ### end Alembic commands ###
